name: "Test"

on:
  push:
    branches: [ "master" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "master" ]
    
jobs:
  nativeLinux:
    name: Native Linux Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip' # caching pip dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt
    - name: Run simple test
      run: |
        cd TestSrc
        make CC=gcc LDFLAGS=
        python ../WCS.py
  arm:
    name: Arm cross compilation Test
    runs-on: ubuntu-latest
    container: dockcross/linux-armv7
    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt
    - name: Run simple test
      run: |
        cd TestSrc
        make CC=${CC} LDFLAGS=
        python ../WCS.py
